### ISSUE TITLE
Tag cloud links to localhost:4242

### ISSUE THREAD

**Issue by CSchulz** [arquillian/arquillian.github.io#376]
##### Issue Overview
Tag cloud on the right side links to localhost:4242

##### Expected Behaviour
Should link to http://arquillian.org/blog/tags/jacoco/

##### Current Behaviour
Links to http://localhost:4242/blog/tags/jacoco/

##### Steps To Reproduce
1. Vist http://arquillian.org/blog/
2. Click on a tag on the right side

**Comment by bartoszmajsak** [comment]
Thanks :) fix on the way

**Comment by MatousJobanek** [comment]
It should be fixed now. Sorry for an inconvenience and thank you for reporting this 🥇
