### ISSUE TITLE
Untranslated parts and truncated sentences in the German translation of the Testing Java Persistence article

### ISSUE THREAD

**Issue by lukegv** [arquillian/arquillian.github.io#390]
##### Issue Overview

There are untranslated parts and truncated sentences in the German translation of the _Testing Java Persistence_ article.

##### Additional Information

I don't know whether this issue is really required, but the template for pull requests told me to create an issue, if the pull request does not resolve an existing issue. Also, my translation fix is just a small improvement, so feel free to apply or ignore it, but I came across your beginner tutorials and saw these mistakes (and the **Edit this file** button at the top of the page), so I decided to fix them.

**Comment by MatousJobanek** [comment]
Hi,
thx for reporting and fixing it. The issue wasn't really necessary, but it's good to have. 
You can think that your translation fix is just a small improvement, but for us, it brings a big value to the overall quality of our web pages and makes the reading more fluent. 
If you find any additional discrepancies, we will be more than happy if you help us with fixing it.
Thanks!

**Comment by bartoszmajsak** [comment]
Yeah, awesome work @lukegv! Thanks a lot.
