### ISSUE TITLE
Confusing usage of info class

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian.github.io#405]
![image](https://user-images.githubusercontent.com/719616/32989395-5d1263a2-cd15-11e7-9275-b021f54145ba.png)

PR #403 brings fix to the English version. It should also be applied to translations.

**Comment by MatousJobanek** [comment]
The problem is that there is missing  percentage sign `%` - the correct form is:
`p(info). %The info text%`

**Comment by bartoszmajsak** [comment]
Ok I will revert previous change and fix - closing this issue too.
