### ISSUE TITLE
Add liberty-arquillian repository

### ISSUE THREAD

**Issue by gpoul** [arquillian/arquillian.github.io#436]
I've tried to add the liberty-arquillian repository but I don't seem to be able to get it to build cleanly or add the required information.

I added the following to the repository.rb:

```
          @repositories << OpenStruct.new(
              :path => 'liberty-arquillian',
              :desc => nil,
              :relative_path => '',
              :owner => 'OpenLiberty',
              :host => 'github.com',
              :type => 'git',
              :html_url => 'https://github.com/OpenLiberty/liberty-arquillian',
              :clone_url => 'git://github.com/OpenLiberty/liberty-arquillian.git'
          )
```

And this seems to add the page itself, but on there the "Lead" and "Family" identifiers were not filled correctly.

Would you be able to give me a hint of what would be required to integrate this so I can submit an appropriate PR?

Thanks!

**Comment by gpoul** [comment]
Turns out my issues seem to be related to the _tmp/datacache that I didn't clear so my code changes where not addressed... I've now opened the above PR, but not sure if I'm still missing something that might be important.

**Comment by MatousJobanek** [comment]
Hi @gpoul,
I saw you PR, so I'll move the discussion there.

**Comment by MatousJobanek** [comment]
closed via https://github.com/arquillian/arquillian.github.io/pull/437
